before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g cleverstack-cli

before_script:
  - mysql -e 'create database test_db;'
  - export NODE_ENV=test
  - export NODE_PATH=./lib/:./modules/
  - node tests/before_travis_test.js

script:
  - "npm test"

notifications:
  email:
    - nailuii@gmail.com
  slack:
    rooms:
      - cycle-o-maniacs:J9kpzC3EigEPmGTslJ5BP3jU#general
      - cycle-o-maniacs:J9kpzC3EigEPmGTslJ5BP3jU#random

env:
  - NODE_ENV=test; NODE_PATH=./lib/:./modules/

language: node_js

node_js:
  - '6.0'
  - '7'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

sudo: false
